<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\air fryer.jpg" />
    <None Remove="Resources\airfryer.jpg" />
    <None Remove="Resources\IMG_4547.jpg" />
    <None Remove="Resources\xdd-xdding.gif" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\airfryer.jpg" />
    <Resource Include="Resources\IMG_4547.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="AddWordWindow.xaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
